<a href="https://colab.research.google.com/github/meninblack110/Distance_and_time/blob/main/Distance_and_time_Starter_Code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Starter Code

# Exploring NumPy Arrays: Distance and Time

1) Import the numpy library

In [2]:
import numpy as np

2) Create a numpy array called "distance" that includes the following distances (in meters): 100, 200, 400, 800, 1500, 3000, 5000, 10000

In [4]:
distance= np.array([100, 200, 400, 800, 1500, 3000, 5000, 10000])

In [5]:
distance

array([  100,   200,   400,   800,  1500,  3000,  5000, 10000])

3) Use the np.min() and np.max() functions to find the minimum and maximum distances

In [6]:
distance.min()

100

4) To find the average distance, use the np.mean() function

In [7]:
distance.max()

10000

5) use the np.sum() function to find the total distance

In [8]:
distance.sum()

21000

6) Another valuable function is the np.cumsum() function which outputs the cumulative sum...notice the output will be 100, 300, 700 as it adds each new distance

In [9]:
distance.cumsum()

array([  100,   300,   700,  1500,  3000,  6000, 11000, 21000])

7) To round all of the values in an array, use np.round()

In [10]:
distance.round()

array([  100,   200,   400,   800,  1500,  3000,  5000, 10000])

8) Create a numpy array called time that includes the following times (in seconds):  10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45

In [11]:
time= np.array([10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45])
time

array([  10.62,   21.34,   48.25,  113.43,  233.96,  506.53,  866.17,
       1757.45])

9) the values in your time array correspond to olympic records for running the corresponding distances.  Perform the calculation needed to find the speed (in m/s) for each record distance.  Note that speed is distance divided by time.

In [12]:
speed= time/distance
speed

array([0.1062    , 0.1067    , 0.120625  , 0.1417875 , 0.15597333,
       0.16884333, 0.173234  , 0.175745  ])

10) One common problem data scientists run into is that we are given information in units that are not consistent.  
For example, we might want to compare data that is given in meters to second to data that is given in miles per hour. A cheetah is the fastest land animal which can reach speeds of 75.0 miles per hour.  
In order to compare our olympians to a cheetah, we need to be able to convert from one unit to another.
Perform calculations to convert the olympic record speeds from meters/second into miles per hour.  Note: 1 meter = 0.00062 miles

How do our olympians compare to the cheetah?

(Hint: Speed in m/s multiplied by 0.00062 and multiplied by 3600 will give speed in miles per hour)

In [13]:
speed*0.00062*3600

array([0.2370384 , 0.2381544 , 0.269235  , 0.3164697 , 0.34813248,
       0.37685832, 0.38665829, 0.39226284])